### ISSUE TITLE
Collect datasets for Sound categories

### ISSUE THREAD

**Issue by pradyumnad** [LoadedCoders/iHear#1]

**Comment by pradyumnad** [comment]
https://www.audiocontentanalysis.org/data-sets/

**Comment by pradyumnad** [comment]
@bharath-attaluri Did you go through these ? for the audio classification dataset.

**Comment by bharath-attaluri** [comment]
going on, will finish it asap

**Comment by pradyumnad** [comment]
Found these interesting for our need.
http://www.cs.tut.fi/~heittolt/datasets
